application: keepintouch
version: 1
runtime: php
api_version: 1

handlers:
- url: /js
  static_dir: templates/js
- url: /img
  static_dir: templates/img
- url: /css
  static_dir: templates/css
- url: /.*
  script: main.php
